export type MusicStreamValue =
  | "id"
  | "name"
  | "isLooping"
  | "isQueueLooping"
  | "isAutoPlaying"
  | "isPlaying"
  | "isPaused"
  | "streamDispatcher"
  | "voiceConnection"
  | "tempChannelId"
  | "nextPage"
  | "queue"
  | "boundVoiceChannel"
  | "boundTextChannel"
  | "leaveOnTimeout";
