version: '3.8'
name: YuiTS_Bot
services:
  yui_bot:
    container_name: YuiNoIe # 唯の家 
    build:
      context: .
      dockerfile: Dockerfile.multistage
    environment:
      NODE_ENV: build
    ports:
     - 443:443
     - 80:80