version: '3.8'
services:
  yui-bot:
    container_name: YuiNoIe # 唯の家 
    build: .
    environment:
      NODE_ENV: build
    ports:
     - 443:443
     - 80:80
    depends_on:
      - redis
  redis:
    container_name: redis_service
    image: redis:latest
    ports:
      - 6379:6379